name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cd to ./engine
      run: cd engine
    - name: ls
      run: ls
    # - name: make
    #   run: make
