name: Debian

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye

    steps:
    - name: Install image dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git nodejs npm

    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: npm install UI packages
      run: npm i

    - name: npm install webpack packages
      run: npm i
      working-directory: ./scripts

    - name: compile source libs
      run: npx tsc
      working-directory: ./src

    - name: install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libgtk-3-0 \
            libwebkit2gtk-4.1-0 \
            pkg-config \
            libboost-all-dev
            
    - name: make
      run: make run
      working-directory: ./engine
