name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Install Boost 1.82
      run: |
        $boost_installer_path = "C:\boost_installer.exe"
        Invoke-WebRequest -Uri https://boostorg.jfrog.io/artifactory/main/release/1.82.0/binaries/boost_1_82_0-msvc-14.2-64.exe -OutFile $boost_installer_path
        if (-Not (Test-Path $boost_installer_path)) {
          Write-Error "Boost installer not found!"
        }
        Start-Process -FilePath $boost_installer_path -ArgumentList "/quiet", "/dir=C:\boost_1_82" -Wait      
    - name: Set up environment variables
      run: |
        echo "BOOST_ROOT=C:\boost_1_82" >> $GITHUB_ENV
        echo "BOOST_LIBRARYDIR=C:\boost_1_82\lib64-msvc-14.2" >> $GITHUB_ENV
        echo "BOOST_INCLUDE=C:\boost_1_82" >> $GITHUB_ENV

    - name: npm install UI packages
      run: npm i

    - name: npm install script packages
      run: npm i
      working-directory: ./scripts

    - name: compile source libs
      run: npm run compile:ts
        
    - name: make
      run: make run
      working-directory: ./engine
