name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Install python for boost compilation
      run: |
        choco install python3

    - name: Download Boost source
      run: |
        git clone --branch boost-1.82.0 https://github.com/boostorg/boost.git

    - name: Build Boost
      run: |
        cd boost
        bootstrap.bat
        .\b2.exe --toolset=msvc-14.2 --prefix="C:\boost" install

    - name: npm install UI packages
      run: npm i

    - name: npm install script packages
      run: npm i
      working-directory: ./scripts

    - name: compile source libs
      run: npm run compile:ts
        
    - name: make
      run: make run
      working-directory: ./engine
