name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Get boost installer
      run: |
        curl -L https://sourceforge.net/projects/boost/files/boost-binaries/1.82.0/boost_1_82_0-msvc-14.1-64.exe/download -o C:\boost_1_82_0.exe
        # Get-Content C:\boost_1_82_0.zip -TotalCount 50
        
    - name: Run boost installer
      run: |
        C:\boost_1_82_0.exe /S
        dir "C:\"
        dir "C:\boost"
    
    - name: Set Boost paths
      run: |
        dir
        echo "INCLUDE=C:\ProgramData\chocolatey\lib\boost-msvc-14.1\unpacked\tools\boost\include;$env:INCLUDE" >> $env:GITHUB_ENV
        echo "LIB=C:\ProgramData\chocolatey\lib\boost-msvc-14.1\unpacked\tools\boost\lib;$env:LIB" >> $env:GITHUB_ENV
        echo $INCLUDE
        echo $LIB

    - name: npm install UI packages
      run: npm i

    - name: npm install script packages
      run: npm i
      working-directory: ./scripts

    - name: compile source libs
      run: npm run compile:ts
        
    - name: make
      run: |
        git --version
        ls
        make
      working-directory: ./engine
      shell: bash
