name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: npm install UI packages
      run: npm i

    - name: npm install script packages
      run: npm i
      working-directory: ./scripts

    - name: compile source libs
      run: npm run compile:ts

    - name: install deps
      run: choco install -y \
        boost-msvc-14.3
        
    - name: make
      run: make run
      working-directory: ./engine
