name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Install boost
      run: |
        $installer_url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.82.0/boost_1_82_0-msvc-14.3-64.exe/download"
        $installer_path = "C:\boost-installer.exe"
        Invoke-WebRequest -Uri $installer_url -OutFile $installer_path
        if (-Not (Test-Path $installer_path)) {
          Write-Error "Installer not found at $installer_path"
          exit 1
        }

    - name: Run boost installer
      run: |
        $installer_path = "C:\boost-installer.exe"
        Start-Process -FilePath $installer_path -ArgumentList "/silent", "/dir=C:\install-dir" -Wait

    - name: npm install UI packages
      run: npm i

    - name: npm install script packages
      run: npm i
      working-directory: ./scripts

    - name: compile source libs
      run: npm run compile:ts
        
    - name: make
      run: make run
      working-directory: ./engine
      shell: sh
