name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Download boost
      run: |
        curl -L https://archives.boost.io/release/1.82.0/source/boost_1_82_0.zip -o C:\boost_1_82_0.zip
        
    - name: Unzip boost
      run: |
        Expand-Archive -Path "C:\boost_1_82_0.zip" -DestinationPath "C:\boost"
        dir "C:\"
        dir "C:\boost"
        dir "C:\boost\boost_1_82_0"

    - name: Compile boost
      run: |
        cd C:\boost\boost_1_82_0
        .\bootstrap.bat
        .\b2.exe toolset=msvc-14.1 address-model=64 link=static runtime-link=static threading=multi variant=debug stage  
        dir "C:\boost\boost_1_82_0\stage"
        dir "C:\boost\boost_1_82_0\stage\lib"
  
    - name: Set Boost paths
      run: |
        dir
        echo "INCLUDE=C:\boost\boost_1_82_0;$env:INCLUDE" >> $env:GITHUB_ENV
        echo "LIB=C:\boost\boost_1_82_0\stage\lib;$env:LIB" >> $env:GITHUB_ENV
        echo $INCLUDE
        echo $LIB

    - name: npm install UI packages
      run: npm i

    - name: npm install script packages
      run: npm i
      working-directory: ./scripts

    - name: compile source libs
      run: npm run compile:ts
        
    - name: make
      run: |
        git --version
        ls
        make
      working-directory: ./engine
      shell: bash
