name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install boost
      run: choco install boost-msvc-14.1

    - name: Unzip boost package
      run: |
        Expand-Archive -Path "C:\ProgramData\chocolatey\lib\boost-msvc-14.1\boost-msvc-14.1.nupkg" ` -DestinationPath "C:\ProgramData\chocolatey\lib\boost-msvc-14.1\unpacked"

    - name: Set Boost paths
      run: |
        dir C:\ProgramData\chocolatey\lib\boost-msvc-14.1
        dir C:\ProgramData\chocolatey\lib\boost-msvc-14.1\unpacked
        echo "INCLUDE=C:\ProgramData\chocolatey\lib\boost-msvc-14.1\unpacked\tools\boost\include;$env:INCLUDE" >> $env:GITHUB_ENV
        echo "LIB=C:\ProgramData\chocolatey\lib\boost-msvc-14.1\unpacked\tools\boost\lib;$env:LIB" >> $env:GITHUB_ENV
        echo $INCLUDE
        echo $LIB

    - name: npm install UI packages
      run: npm i

    - name: npm install script packages
      run: npm i
      working-directory: ./scripts

    - name: compile source libs
      run: npm run compile:ts
        
    - name: make
      run: |
        git --version
        ls
        make
      working-directory: ./engine
      shell: bash
