name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install NSIS
      uses: repolevedavaj/install-nsis@v1.0.1
      with:
        nsis-version: '3.10'

    - name: Install 7zip
      run: choco install 7zip -y

    - name: Get boost installer
      run: |
        curl -L https://github.com/MarkusJx/prebuilt-boost/releases/download/1.82.0/boost-1.82.0-windows-2022-msvc-static-x86.tar.gz -o C:\boost_1_82_0.tar.gz
        # Get-Content C:\boost_1_82_0.zip -TotalCount 50
        
    - name: Run boost installer
      run: |
        7z x C:\boost_1_82_0.tar.gz -oC:\local\boost_1_82_0        
        dir "C:\"
        dir "C:\local\boost_1_82_0"
    
    - name: Install boost
      uses: MarkusJx/install-boost@v2
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here:
        # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
        boost_version: 1.82.0
        # OPTIONAL: Specify a platform version
        platform_version: 2022
        # OPTIONAL: Specify a toolset
        toolset: msvc
        link: static

    - name: Try input
      run: |
        dir
        dir C:\

    - name: Set Boost paths
      run: |
        dir
        echo "INCLUDE=C:\local\boost_1_82_0;$env:INCLUDE" >> $env:GITHUB_ENV
        echo "LIB=C:\local\boost_1_82_0\lib64-msvc-14.1;$env:LIB" >> $env:GITHUB_ENV
        echo $INCLUDE
        echo $LIB

    - name: npm install UI packages
      run: npm i

    - name: npm install script packages
      run: npm i
      working-directory: ./scripts

    - name: compile source libs
      run: npm run compile:ts
        
    - name: make
      run: |
        git --version
        ls
        make
      working-directory: ./engine
      shell: bash
